### ISSUE TITLE
🐞 - `requestAnimationFrame is not a function` error on server side (SSR)

### ISSUE THREAD

**Issue by NazirTemirov** [Tinkoff/taiga-ui#1671]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Description

Steps for reproduction:
1. Create a new angular project - `ng new ng-13`
2. Add server side rendering - `ng add @nguniversal/express-engine`
3. Add taiga ui - `ng add taiga-ui`
4. Run an application with ssr - `npm run dev:ssr`

You will see the following error in a console:
```
ERROR TypeError: requestAnimationFrame is not a function
    at Observable._subscribe (C:\...\ng-13\dist\ng-13\server\main.js:515:18)
    at Observable._trySubscribe (C:\...\ng-13\dist\ng-13\server\main.js:78046:25)
    at C:\...\ng-13\dist\ng-13\server\main.js:78040:31
    at Object.errorContext (C:\...\ng-13\dist\ng-13\server\main.js:87011:9)
    at Observable.subscribe (C:\...\ng-13\dist\ng-13\server\main.js:78031:24)
    at C:\...\ng-13\dist\ng-13\server\main.js:83813:37
    at OperatorSubscriber.<anonymous> (C:\...\ng-13\dist\ng-13\server\main.js:87502:28)
    at C:\...\ng-13\dist\ng-13\server\main.js:78035:30
    at Object.errorContext (C:\...\ng-13\dist\ng-13\server\main.js:87011:9)
    at Observable.subscribe (C:\...\ng-13\dist\ng-13\server\main.js:78031:24)
```

If remove `<tui-root></tui-root>` wrapper from an app.component.html, the error disappears.

### Angular version

13.3.2

### Taiga UI version

2.42.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
For SSR you can add our package:
https://github.com/ng-web-apis/universal
I'll keep this issue open so we can document that

**Comment by NazirTemirov** [comment]
@waterplea, thanks for the quick response.
The package doesn't support angular 13, so I installed it with '--force' flag. Seems it woks fine.
I opened an issue - https://github.com/ng-web-apis/universal/issues/32.

**Comment by waterplea** [comment]
> @waterplea, thanks for the quick response.
> The package doesn't support angular 13, so I installed it with '--force' flag. Seems it woks fine.
> I opened an issue - https://github.com/ng-web-apis/universal/issues/32.

Version 1.x supports Angular 9+ and View Engine, version 2.x supports Angular 12+ and Ivy only. You shouldn't need force flag in Angular 13.

**Comment by NazirTemirov** [comment]
Yes, I was wrong. I can install `@ng-web-apis/universal` without `--force` in a pure angular 13 app.
But if I add taiga ui first and then try to install `@ng-web-apis/universal`, I get this error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: ng-13@0.0.0
npm ERR! Found: @ng-web-apis/common@1.13.0
npm ERR! node_modules/@ng-web-apis/common
npm ERR!   peer @ng-web-apis/common@">=1.1.0" from @ng-web-apis/intersection-observer@2.1.0
npm ERR!   node_modules/@ng-web-apis/intersection-observer
npm ERR!     @ng-web-apis/intersection-observer@"^2.1.0" from @taiga-ui/kit@2.42.0
npm ERR!     node_modules/@taiga-ui/kit
npm ERR!       @taiga-ui/kit@"^2.42.0" from the root project
npm ERR!   peer @ng-web-apis/common@">=1.1.0" from @ng-web-apis/mutation-observer@1.1.0
npm ERR!   node_modules/@ng-web-apis/mutation-observer
npm ERR!     @ng-web-apis/mutation-observer@"^1.1.0" from @taiga-ui/cdk@2.42.0
npm ERR!     node_modules/@taiga-ui/cdk
npm ERR!       peer @taiga-ui/cdk@">=2.42.0" from @taiga-ui/core@2.42.0
npm ERR!       node_modules/@taiga-ui/core
npm ERR!         peer @taiga-ui/core@">=2.42.0" from @taiga-ui/kit@2.42.0
npm ERR!         node_modules/@taiga-ui/kit
npm ERR!         1 more (the root project)
npm ERR!       2 more (@taiga-ui/kit, the root project)
npm ERR!     peer @ng-web-apis/mutation-observer@">=1.1.0" from @taiga-ui/core@2.42.0
npm ERR!     node_modules/@taiga-ui/core
npm ERR!       peer @taiga-ui/core@">=2.42.0" from @taiga-ui/kit@2.42.0
npm ERR!       node_modules/@taiga-ui/kit
npm ERR!         @taiga-ui/kit@"^2.42.0" from the root project
npm ERR!       1 more (the root project)
npm ERR!     1 more (@taiga-ui/kit)
npm ERR!   4 more (@ng-web-apis/resize-observer, @taiga-ui/cdk, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @ng-web-apis/universal@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @ng-web-apis/common@2.0.0
npm ERR! node_modules/@ng-web-apis/common
npm ERR!   peer @ng-web-apis/common@">=2.0.0" from @ng-web-apis/universal@2.0.0
npm ERR!   node_modules/@ng-web-apis/universal
npm ERR!     @ng-web-apis/universal@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by waterplea** [comment]
That's because Taiga UI 2.x is still on Angular 9. So it uses @ng-web-apis/common 1.x and @ng-web-apis/universal 2.x respects common 2.x.

You can install universal latest 1.x. This quarter we plan to release Taiga UI 3.0 with Ivy distribution and then all Ivy libraries will be compatible.

**Comment by NazirTemirov** [comment]
Ok, got it.
