### ISSUE TITLE
🐞 - Get error when working with input field and then periodically after that 

### ISSUE THREAD

**Issue by bayburin** [Tinkoff/taiga-ui#2114]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Non-Blocking

### Description

Sometimes I see error into browser console. The error appears sometimes when working with input fields, after which it periodically appears even if nothing is done on the site
```
TypeError: Right-hand side of 'instanceof' is not an object
    at tuiAssertIsHTMLElement (taiga-ui-cdk-classes.js:15:1)
    at TuiHoveredDirective.movedOut (taiga-ui-cdk-directives-hovered.js:10:27)
    at TuiHoveredDirective.value (tinkoff-ng-event-plugins.js:580:1)
    at TuiHoveredDirective_mouseout_silent_HostBindingHandler (taiga-ui-cdk-directives-hovered.js:26:340)
    at executeListenerWithErrorHandling (core.mjs:15031:1)
    at wrapListenerIn_markDirtyAndPreventDefault (core.mjs:15069:1)
    at HTMLElement.<anonymous> (platform-browser.mjs:466:38)
    at HTMLElement.sentryWrapped (helpers.js:74:23)
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Zone.runTask (zone.js:178:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:1)
    at invokeTask (zone.js:1648:1)
    at globalCallback (zone.js:1679:1)
    at HTMLElement.globalZoneAwareCallback (zone.js:1712:1)
```

Perhaps the error raises when working with autocomplete of the input field.
html code of input:
```
    <tui-input-number formControlName="standardSpeed" tuiTextfieldSize="m" postfix="км/ч">
      Нормативная скорость
      <input tuiTextfield name="standardSpeed" />
    </tui-input-number>
```

### Angular version

13.3.10

### Taiga UI version

2.53.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
Most likely the issue here is the "HTMLElement.sentryWrapped" part. Are you using "Sentry" for error reporting?

**Comment by expdts** [comment]
I started getting this error too. She hasn't appeared before.
Checked on Angular versions: 12.2.16, 13.0.0, 13.3.11.

**Comment by bayburin** [comment]
> Most likely the issue here is the "HTMLElement.sentryWrapped" part. Are you using "Sentry" for error reporting?

Yes, I'm using Sentry. Could you suggest how to fix this?

**Comment by splincode** [comment]
<img width="411" alt="image" src="https://user-images.githubusercontent.com/12021443/179248529-8a6062e1-4b05-48fd-8a41-b0c253ef0759.png">
