### ISSUE TITLE
🐞 - `InputSlider` bug with initial control value > 100

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#2259]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/input-slider-initial-value-bug?file=src/app/app.component.ts

### Is this issue blocking you?

Blocking

### Description

```ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: `my-app`,
  template: `
    <tui-root>
        <tui-input-slider
            [min]="min"
            [max]="max"
            [formControl]="control"
        ></tui-input-slider>
    </tui-root>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  readonly min = 0;
  readonly max = 120_000;

  readonly control = new FormControl(101); // ERROR
  // readonly control = new FormControl(100); // NO ERROR
}

```

### Error
```
TuiInputSliderComponent.html:1 ERROR
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at __read (tslib.es6.js:137:46)
    at Object.tuiPercentageToKeyStepValue (key-steps.ts:20:12)
    at TuiSliderKeyStepsDirective.get [as controlValue] (slider-key-steps.directive.ts:77:16)
    at Object.eval [as updateRenderer] (TuiInputSliderComponent.html:39:5)
    at Object.debugUpdateRenderer [as updateRenderer] (services.ts:414:19)
    at checkAndUpdateView (view.ts:381:12)
    at callViewAction (view.ts:628:11)
    at execComponentViewsAction (view.ts:572:7)
    at checkAndUpdateView (view.ts:383:3)
    at callViewAction (view.ts:628:11)
```

### Angular version

any

### Taiga UI version

2.56.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
Bug happens inside `Slider` (`[ngModel]` + `[keySteps]`).

Minimum reproduction:
https://stackblitz.com/edit/slider-initial-value-bug?file=src/app/app.component.ts
