### ISSUE TITLE
📚 - `Combobox` examples don't work in Stackblitz

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#3072]
### Description

1. https://taiga-ui.dev/components/combo-box#wrapper
2. Press "Edit on Stackblitz"
3. Open dropdown with options

It throws several errors:
<details>
<summary>ERROR TypeError: Class constructor ElementRef cannot be invoked without 'new' (fixed #3167)</summary>

```
ERROR TypeError: Class constructor ElementRef cannot be invoked without 'new'
    at new TuiElementDirective (element.directive.ts:9:9)
    at NodeInjectorFactory.TuiElementDirective_Factory [as factory] (ɵfac.js? [sm]:1:1)
    at getNodeInjectable (di.ts:636:15)
    at instantiateAllDirectives (shared.ts:1229:7)
    at createDirectivesInstances (shared.ts:556:2)
    at ɵɵelementStart (element.ts:152:3)
    at TuiDataListWrapperComponent_tui_data_list_0_button_1_Template (ɵcmp.js? [sm]:16:13)
    at executeTemplate (shared.ts:522:4)
    at renderView (shared.ts:326:6)
    at TemplateRef.createEmbeddedView (view_container_ref.ts:271:12)
```
</details>

<details>
<summary>ExpressionChangedAfterItHasBeenCheckedError</summary>

```
ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError:
Expression has changed after it was checked.
Previous value: 'undefined'. Current value: 'listbox'.
It seems like the view has been created after its parent and its children have been dirty checked.
Has it been created in a change detection hook? Find more at https://angular.io/errors/NG0100
    at throwErrorIfNoChangesMode (errors.ts:110:5)
    at bindingUpdated (bindings.ts:85:9)
    at ɵɵattribute (interpolation.ts:18:1)
    at TuiDataListComponent_HostBindings (ɵcmp.js:0:0)
    at processHostBindingOpCodes (shared.ts:101:9)
    at refreshView (shared.ts:447:8)
    at refreshEmbeddedViews (shared.ts:1595:58)
    at refreshView (shared.ts:421:6)
    at refreshComponent (shared.ts:1646:11)
    at refreshChildComponents (shared.ts:138:3)
```
</details>

<img width="1505" alt="Screenshot 2022-11-16 at 14 36 35" src="https://user-images.githubusercontent.com/35179038/202170531-8d9588b7-bb20-452c-a9f2-9a5e6d9aa509.png">

### Which browsers have you used?
Chrome

### Which operating systems have you used?
macOS

**Comment by nsbarsukov** [comment]
## Minimum error reproduction:

`Combobox` uses [Element](https://taiga-ui.dev/directives/element)-directive inside.
This directive throws error.

<details open>
<summary> <strong>app.component.ts</strong> </summary>

```ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: `my-app`,
  template: `<p tuiElement #elementRef="elementRef"> ERROR! </p>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {}
```

</details>

<details>
<summary> <strong>app.module.ts</strong> </summary>

```ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { RouterModule } from '@angular/router';
import { TuiElementModule } from '@taiga-ui/cdk';

import { AppComponent } from './app.component';

@NgModule({
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    RouterModule.forRoot([]),
    TuiElementModule,
  ],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

</details>

**Stackblitz reproduction:** https://stackblitz.com/edit/tui-element-type-error?file=src%2Fapp%2Fapp.component.ts

**Comment by nsbarsukov** [comment]
Possibly related issue: https://github.com/stackblitz/core/issues/475

**Comment by nsbarsukov** [comment]
- #3167
