### ISSUE TITLE
🐞 - SSR error `TypeError: Cannot read properties of undefined (reading 'type')`

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#3210]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-doc

### Please provide a link to a minimal reproduction of the bug

See description

### Is this issue blocking you?

Non-Blocking

### Taiga UI repo
1. Run `nx serve-ssr`
2. Open any doc page. For example: `/components/button`

It throws error:
```
ERROR TypeError: Cannot read properties of undefined (reading 'type')
    at TokenStream.LA (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:136421:30)
    at TokenStream.advance (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:136294:20)
    at Parser._readDeclarations (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:139013:42)
    at Parser.parseStyleAttribute (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:139192:22)
    at parseStyles (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:118199:10)
    at CSSStyleDeclaration.get (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:118214:28)
    at CSSStyleDeclaration.value (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:118270:17)
    at CSSStyleDeclaration.get (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:118738:19)
    at cloakElement (/Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:6195:36)
    at /Users/n.barsukov/WebstormProjects/taiga-ui/dist/demo/server/main.js:6201:48
```

### Maskito repo
This error can be also reproduced in another repo:
https://github.com/Tinkoff/maskito

This repo uses `@taiga-ui/addon-doc`.

1. Run `nx serve-ssr`
2. Open `/kit/time`

___

I don't know is it problem of `@taiga-ui/addon-doc` or not.
Need investigation.

### Angular version

12

### Taiga UI version

3.11.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
The problem happens because of this line (almost all documentation tabs has `<tui-tabs />`):
https://github.com/Tinkoff/taiga-ui/blob/0d4f52a72d4b50b4bbfcb25cc7b861ecc63d48cd/projects/kit/components/tabs/tab/tab.component.ts#L27

If you comment this line, the error disappears.

**Why?**
This is a problem with the domino renderer that Angular uses for its server-side DOM implementation. Domino doesn't support CSS variables and some CSS properties like clip-path.
So, any host-binding with CSS variables causes this error :harold-smile:

Read more:
* https://github.com/angular/angular/issues/47928#issuecomment-1298225642
* https://github.com/angular/angular/issues/42170#issuecomment-1299657257
