### ISSUE TITLE
🐞 - tuiDefaultProp decorator throws in rare cases

### ISSUE THREAD

**Issue by DerSizeS** [Tinkoff/taiga-ui#3584]
### Which @taiga-ui/* package(s) are the source of the bug?

cdk

### Is this issue blocking you?

Non-Blocking

### Description

```
TypeError: Cannot redefine property: limitWidth
  at Function.defineProperty(<anonymous>)
  at limitWidth(webpack:/./node_modules/@taiga-ui/cdk/__ivy_ngcc__/fesm2015/taiga-ui-cdk-decorators.js:28:24)
  at useFactory(webpack:/./node_modules/@taiga-ui/kit/__ivy_ngcc__/fesm2015/taiga-ui-kit-providers.js:28:15)
  at factory(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11541:38)
  at getNodeInjectable(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3561:44)
  at searchTokensOnInjector(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3498:16)
  at getOrCreateInjectable(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3442:38)
  at injectInjectorOnly(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14756:12)
  at ɵɵinject(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:4774:42)
  at injectArgs(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:4851:23)
  at factory(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11541:52)
  at getNodeInjectable(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3561:44)
  at searchTokensOnInjector(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3498:16)
  at getOrCreateInjectable(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3442:38)
  at ɵngcc0(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14756:12)
  at factory(webpack:/./node_modules/@taiga-ui/core/__ivy_ngcc__/fesm2015/taiga-ui-core-components-hosted-dropdown.js:169:167)
  at getNodeInjectable(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3561:44)
  at instantiateAllDirectives(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:10298:27)
  at createDirectivesInstances(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9647:5)
  at ɵngcc0(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14900:9)
  at templateFn(webpack:/./node_modules/@taiga-ui/kit/__ivy_ngcc__/fesm2015/taiga-ui-kit-components-input.js:98:9)
  at executeTemplate(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9618:9)
  at renderView(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9421:13)
  at renderComponent(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:10702:5)
  at renderChildComponents(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9286:9)
  at renderView(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9446:13)
  at renderComponent(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:10702:5)
  at renderChildComponents(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9286:9)
  at renderView(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9446:13)
  at createEmbeddedView(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:23045:9)
  at createEmbeddedView(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:23176:37)
  at new g(webpack:/./node_modules/@taiga-ui/cdk/__ivy_ngcc__/fesm2015/taiga-ui-cdk-directives-let.js:26:23)
  at factory(webpack:/./node_modules/@taiga-ui/cdk/__ivy_ngcc__/fesm2015/taiga-ui-cdk-directives-let.js:38:69)
  at getNodeInjectable(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3561:44)
  at instantiateAllDirectives(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:10298:27)
  at createDirectivesInstances(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9647:5)
  at i0(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:13639:9)
  ```
  
  
  ```
  TypeError: Cannot redefine property: limitWidth
  at Function.defineProperty(<anonymous>)
  at limitWidth(webpack:/./node_modules/@taiga-ui/cdk/__ivy_ngcc__/fesm2015/taiga-ui-cdk-decorators.js:28:24)
  at useFactory(webpack:/./node_modules/@taiga-ui/kit/__ivy_ngcc__/fesm2015/taiga-ui-kit-providers.js:28:15)
  at factory(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11541:38)
  at getNodeInjectable(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3561:44)
  at searchTokensOnInjector(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3498:16)
  at getOrCreateInjectable(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3442:38)
  at injectInjectorOnly(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14756:12)
  at ɵɵinject(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:4774:42)
  at injectArgs(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:4851:23)
  at factory(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:11541:52)
  at getNodeInjectable(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3561:44)
  at searchTokensOnInjector(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3498:16)
  at getOrCreateInjectable(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3442:38)
  at ɵngcc0(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14756:12)
  at factory(webpack:/./node_modules/@taiga-ui/core/__ivy_ngcc__/fesm2015/taiga-ui-core-components-hosted-dropdown.js:169:167)
  at getNodeInjectable(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:3561:44)
  at instantiateAllDirectives(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:10298:27)
  at createDirectivesInstances(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9647:5)
  at ɵngcc0(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14900:9)
  at templateFn(webpack:/./node_modules/@taiga-ui/kit/__ivy_ngcc__/fesm2015/taiga-ui-kit-components-select.js:144:9)
  at executeTemplate(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9618:9)
  at renderView(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9421:13)
  at renderComponent(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:10702:5)
  at renderChildComponents(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9286:9)
  at renderView(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:9446:13)
  at createEmbeddedView(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:23045:9)
  at createEmbeddedView(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:23176:37)
  at _updateView(webpack:/./node_modules/@angular/common/__ivy_ngcc__/fesm2015/common.js:3463:45)
  at privateName(webpack:/./node_modules/@angular/common/__ivy_ngcc__/fesm2015/common.js:3436:14)
  at setInputsForProperty(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:10979:22)
  at elementPropertyInternal(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:10023:9)
  at i0(webpack:/./node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:14806:9)
  ```

### Angular version

12.2.16

### Taiga UI version

2.74.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I think now, that Angular itself protects against undefined inputs we can, probably, drop this decorator, what do you think, @splincode @nsbarsukov @vladimirpotekhin ?

**Comment by splincode** [comment]
Sure, we can do it, I like it
