### ISSUE TITLE
🐞 - SVG tuiSvgLinearGradientProcessor is still buged

### ISSUE THREAD

**Issue by squelix** [Tinkoff/taiga-ui#4045]
### Playground Link

https://stackblitz.com/edit/angular-v97usx-fcjr6m

### Description

Hi ! When there is a linearGradient with id in a svg icon, the id processing is not working in version 3.22.0 but when i downgrade the version to 3.21.0 it's working.

For example when i am using this following SVG, i'm getting this following error. 

> Edit: When i'm using SVG in plain text it's working but when i'm using it as a link with the SVG, it's not working anymore. 

```shell
ERROR SyntaxError: Invalid regular expression: /Dégradé_sans_nom_34)"></path><path d="M960.58 320.37a127.5 127.5 0 0 1 0 255Z" fill="url(#Dégradé_jeunes)"></path><path d="M960.58 320.37a127.5 127.5 0 0 1 0 255Z" style="mix-blend-mode:multiply" opacity=".7" fill="url(#Dégradé_sans_nom_47/: Unmatched ')' (at taiga-ui-cdk-utils-svg.js:20:78)
    at new RegExp (<anonymous>)
    at taiga-ui-cdk-utils-svg.js:20:78
    at Array.reduce (<anonymous>)
    at Object.e [as contentProcessor] (taiga-ui-cdk-utils-svg.js:20:26)
    at ht.sanitize (taiga-ui-core-components-svg.js:205:28)
    at taiga-ui-core-components-svg.js:215:34
    at map.js:7:37
    at c._next (OperatorSubscriber.js:13:21)
    at c.next (Subscriber.js:31:18)
    at c._next (Subscriber.js:60:26)
```

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="723.08 270.37 473.6 610.64">
   <defs>
      <linearGradient id="Dégradé_sans_nom_33" x1="760.69" y1="1283.83" x2="1159.31" y2="-203.83" gradientUnits="userSpaceOnUse">
         <stop offset=".11" stop-color="currentColor"></stop>
         <stop offset="1" stop-color="#FFF"></stop>
      </linearGradient>
      <linearGradient id="shadow_jeunes" x1="960.58" y1="540" x2="1381" y2="540" gradientUnits="userSpaceOnUse">
         <stop offset="0" stop-color="#FFF"></stop>
         <stop offset="1" stop-color="currentColor" stop-opacity="0"></stop>
      </linearGradient>
      <linearGradient id="Dégradé_sans_nom_34" x1="896.13" y1="348.34" x2="896.13" y2="673.86" gradientUnits="userSpaceOnUse">
         <stop offset="0" stop-color="#FFF"></stop>
         <stop offset=".89" stop-color="currentColor"></stop>
      </linearGradient>
      <linearGradient id="Dégradé_jeunes" x1="1045.59" y1="523.64" x2="933.88" y2="358.01" xlink:href="#Dégradé_sans_nom_33"></linearGradient>
      <linearGradient id="Dégradé_sans_nom_47" x1="969.97" y1="447.87" x2="1079.19" y2="447.87" gradientUnits="userSpaceOnUse">
         <stop offset="0" stop-color="currentColor" stop-opacity=".6"></stop>
         <stop offset=".14" stop-color="currentColor" stop-opacity=".45"></stop>
         <stop offset=".37" stop-color="currentColor" stop-opacity=".26"></stop>
         <stop offset=".59" stop-color="#00001d" stop-opacity=".11"></stop>
         <stop offset=".8" stop-color="#000007" stop-opacity=".03"></stop>
         <stop offset="1" stop-opacity="0"></stop>
      </linearGradient>
   </defs>
   <g style="isolation:isolate">
      <g id="KVPEP_JEUNES">
         <g id="logo">
            <path id="Cadre" class="cls-4" d="M723.08 270.37v330a150 150 0 0 0 150 150h173.6a150 150 0 0 0 150-150v-330Zm458.6 330a135 135 0 0 1-135 135h-173.6a135 135 0 0 1-135-135V510h443.6Z"></path>
            <g id="P">
               <path d="M931.68 320.37h28.9v380h-28.9a100 100 0 0 1-100-100v-180a100 100 0 0 1 100-100Z" fill="url(#Dégradé_sans_nom_34)"></path>
               <path d="M960.58 320.37a127.5 127.5 0 0 1 0 255Z" fill="url(#Dégradé_jeunes)"></path>
               <path d="M960.58 320.37a127.5 127.5 0 0 1 0 255Z" style="mix-blend-mode:multiply" opacity=".7" fill="url(#Dégradé_sans_nom_47)"></path>
            </g>
            <g id="titre">
               <path class="cls-4" d="M772.67 833.13a14.19 14.19 0 0 1 6.06 5.63 17.83 17.83 0 0 1 0 16.66 14.17 14.17 0 0 1-6.06 5.63 21.09 21.09 0 0 1-9.66 2h-6v16a1 1 0 0 1-1 1h-7.49a1 1 0 0 1-1-1v-46.9a1 1 0 0 1 1-1H763a21.1 21.1 0 0 1 9.67 1.98Zm-3.53 19.67q2.48-1.75 2.48-5.74t-2.52-5.71a10.63 10.63 0 0 0-6.3-1.79h-5.74v15h5.74a10.75 10.75 0 0 0 6.34-1.76ZM808.72 847.48a2.32 2.32 0 0 1-.14.56l-2.1 5.18q-.35 1.05-1.54.7a10 10 0 0 0-2.87-.49 6.75 6.75 0 0 0-5.18 2.1 7.49 7.49 0 0 0-2 5.32V879a1 1 0 0 1-1.05 1h-7.14a1 1 0 0 1-1.05-1v-32.2a1 1 0 0 1 1.05-1h6.79q.91 0 1 1l.28 3.78q3.08-5.6 8.75-5.6a7.26 7.26 0 0 1 4.62 1.61 1.16 1.16 0 0 1 .58.89ZM818.13 878.63a17.49 17.49 0 0 1-6.48-6.51 18.59 18.59 0 0 1 0-18.2 17.76 17.76 0 0 1 30.8 0 18.58 18.58 0 0 1 0 18.2 17.83 17.83 0 0 1-24.32 6.51Zm15.23-8.86a10.1 10.1 0 0 0 0-13.51 8.79 8.79 0 0 0-12.64 0 10.3 10.3 0 0 0 0 13.58 8.79 8.79 0 0 0 12.64 0ZM876.41 834.53a.81.81 0 0 1-.28.56l-3.57 3.5a.79.79 0 0 1-1 .14 11 11 0 0 0-5.32-1.89q-2.38 0-3.19 1.08a5.44 5.44 0 0 0-.8 3.25v4.62h6.93a1 1 0 0 1 1.05 1v5.46a1 1 0 0 1-1.05 1h-6.93V879a1 1 0 0 1-1.05 1h-7.14a1 1 0 0 1-1.05-1v-25.64H849a1 1 0 0 1-1-1v-5.46a1 1 0 0 1 1-1h4V840q0-5.67 3.22-8.54t8.89-2.87a12.44 12.44 0 0 1 6.47 1.64 17.09 17.09 0 0 1 4.58 3.88.61.61 0 0 1 .25.42ZM928.42 865.43a2 2 0 0 1-2 .95h-22a8.35 8.35 0 0 0 3.22 5.29 10.83 10.83 0 0 0 6.58 1.85 12.32 12.32 0 0 0 3.78-.56 12.6 12.6 0 0 0 3.5-1.82 1.21 1.21 0 0 1 .77-.28 1.07 1.07 0 0 1 .77.35l3.08 3a1 1 0 0 1 .35.7 1.21 1.21 0 0 1-.42.84 17.75 17.75 0 0 1-12.68 5.25 18.45 18.45 0 0 1-9.38-2.38 16.73 16.73 0 0 1-6.4-6.48 18.48 18.48 0 0 1-2.27-9.13 18.77 18.77 0 0 1 2.24-9.1A16.79 16.79 0 0 1 912.6 845a15.64 15.64 0 0 1 8.54 2.35 16 16 0 0 1 5.74 6.26 18.45 18.45 0 0 1 2 8.61 7.45 7.45 0 0 1-.46 3.21Zm-21.25-10.6a8.8 8.8 0 0 0-2.83 5.53h16.38a8.67 8.67 0 0 0-2.69-5.53 7.78 7.78 0 0 0-5.35-2 8.13 8.13 0 0 0-5.51 2ZM960.58 846.74a11.66 11.66 0 0 1 4.44 5 17.48 17.48 0 0 1 1.61 7.77V879a1 1 0 0 1-1.05 1h-7.14a1 1 0 0 1-1-1v-17.8q0-4-1.82-5.81a6.26 6.26 0 0 0-4.62-1.82 6.72 6.72 0 0 0-4.1 1.26 8.8 8.8 0 0 0-2.59 2.87 5.88 5.88 0 0 0-.87 2.59V879a1 1 0 0 1-1.05 1h-7.14a1 1 0 0 1-1.05-1v-32.2a1 1 0 0 1 1.05-1h6.86q.91 0 1 1l.28 4.48v.07a14.25 14.25 0 0 1 4.55-4.66 11.6 11.6 0 0 1 6.3-1.71 12 12 0 0 1 6.34 1.76ZM1017 833.13a14.19 14.19 0 0 1 6.06 5.63 17.84 17.84 0 0 1 0 16.66 14.18 14.18 0 0 1-6.06 5.63 21.09 21.09 0 0 1-9.66 2h-5.95v16a1 1 0 0 1-1.05 1h-7.49a1 1 0 0 1-1.05-1v-46.9a1 1 0 0 1 1.05-1h14.49a21.1 21.1 0 0 1 9.66 1.98Zm-3.54 19.67q2.48-1.75 2.49-5.74t-2.52-5.71a10.64 10.64 0 0 0-6.3-1.79h-5.74v15h5.74a10.75 10.75 0 0 0 6.37-1.76ZM1035.69 878.63a17.49 17.49 0 0 1-6.47-6.51 18.58 18.58 0 0 1 0-18.2 17.76 17.76 0 0 1 30.8 0 18.59 18.59 0 0 1 0 18.2 17.83 17.83 0 0 1-24.33 6.51Zm15.22-8.86a10.1 10.1 0 0 0 0-13.51 8.79 8.79 0 0 0-12.63 0 10.3 10.3 0 0 0 0 13.58 8.79 8.79 0 0 0 12.63 0ZM1087.95 871.67a15 15 0 0 0 3.36-2.28 1.07 1.07 0 0 1 .77-.35.93.93 0 0 1 .77.35l4.27 4.06a1.07 1.07 0 0 1 .35.77 1 1 0 0 1-.28.7 17.13 17.13 0 0 1-6 4.48 17.71 17.71 0 0 1-7.49 1.61 17.22 17.22 0 0 1-15.19-8.89 19.07 19.07 0 0 1 0-18.2 17.46 17.46 0 0 1 22.54-7.28 17.35 17.35 0 0 1 5.88 4.48 1 1 0 0 1 .28.7 1.07 1.07 0 0 1-.35.77l-4.27 4.13a1 1 0 0 1-.7.35 1.21 1.21 0 0 1-.84-.42 15.42 15.42 0 0 0-3.33-2.27 8.59 8.59 0 0 0-3.82-.81 8.24 8.24 0 0 0-6.33 2.7 10.43 10.43 0 0 0 0 13.51 8.24 8.24 0 0 0 6.33 2.7 9.16 9.16 0 0 0 4.05-.81ZM1128.79 846.74a11.67 11.67 0 0 1 4.44 5 17.5 17.5 0 0 1 1.61 7.77V879a1 1 0 0 1-1 1h-7.14a1 1 0 0 1-1.05-1v-17.8q0-4-1.82-5.81a6.26 6.26 0 0 0-4.62-1.82 6.72 6.72 0 0 0-4.09 1.26 8.79 8.79 0 0 0-2.59 2.87 5.88 5.88 0 0 0-.87 2.59V879a1 1 0 0 1-1 1h-7.14a1 1 0 0 1-1-1v-49a1 1 0 0 1 1-1h7.14a1 1 0 0 1 1 1v21.4a14.25 14.25 0 0 1 4.55-4.66 11.6 11.6 0 0 1 6.3-1.71 12 12 0 0 1 6.28 1.71ZM1173.21 865.43a2 2 0 0 1-2 .95h-22a8.35 8.35 0 0 0 3.22 5.29 10.83 10.83 0 0 0 6.58 1.85 12.32 12.32 0 0 0 3.78-.56 12.6 12.6 0 0 0 3.5-1.82 1.21 1.21 0 0 1 .77-.28 1.07 1.07 0 0 1 .77.35l3.08 3a1 1 0 0 1 .35.7 1.21 1.21 0 0 1-.42.84 17.75 17.75 0 0 1-12.74 5.25 18.45 18.45 0 0 1-9.38-2.38 16.72 16.72 0 0 1-6.41-6.48 18.49 18.49 0 0 1-2.28-9.13 18.77 18.77 0 0 1 2.24-9.1 16.79 16.79 0 0 1 15-8.89 15.64 15.64 0 0 1 8.54 2.35 16 16 0 0 1 5.74 6.26 18.45 18.45 0 0 1 2 8.61 7.45 7.45 0 0 1-.34 3.19Zm-21.21-10.6a8.8 8.8 0 0 0-2.83 5.53h16.38a8.68 8.68 0 0 0-2.69-5.53 7.78 7.78 0 0 0-5.36-2 8.13 8.13 0 0 0-5.5 2Z"></path>
            </g>
         </g>
      </g>
   </g>
</svg>
```

### Angular version

14.3.0

### Taiga UI version

3.22.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
I will check it, thank you!

**Comment by squelix** [comment]
Ok, I tried again some things, and when i'm using one line SVG it'w not woking anymore, the regexp is maybe only multiline, i did another stackblitz here with examples: https://stackblitz.com/edit/angular-v97usx-1urf3k.

**Comment by squelix** [comment]
This is a working example in 3.21.0 https://stackblitz.com/edit/angular-v97usx-6ym8fx
